// Mocks generated by Mockito 5.4.6 from annotations
// in locaydo_app/test/features/products/product_form_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:locaydo_app/features/products/data/models/product_model.dart'
    as _i4;
import 'package:locaydo_app/features/products/data/models/seller_product_model.dart'
    as _i5;
import 'package:locaydo_app/features/products/data/repositories/product_repository_impl.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepositoryImpl extends _i1.Mock
    implements _i2.ProductRepositoryImpl {
  MockProductRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductModel>> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i3.Future<List<_i4.ProductModel>>.value(
              <_i4.ProductModel>[],
            ),
          )
          as _i3.Future<List<_i4.ProductModel>>);

  @override
  _i3.Future<List<_i4.ProductModel>> getProductsByCategory(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [categoryId]),
            returnValue: _i3.Future<List<_i4.ProductModel>>.value(
              <_i4.ProductModel>[],
            ),
          )
          as _i3.Future<List<_i4.ProductModel>>);

  @override
  _i3.Future<List<_i4.ProductModel>> getProductsBySeller(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsBySeller, [sellerId]),
            returnValue: _i3.Future<List<_i4.ProductModel>>.value(
              <_i4.ProductModel>[],
            ),
          )
          as _i3.Future<List<_i4.ProductModel>>);

  @override
  _i3.Future<List<_i5.SellerProduct>> getSellerProducts(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerProducts, [sellerId]),
            returnValue: _i3.Future<List<_i5.SellerProduct>>.value(
              <_i5.SellerProduct>[],
            ),
          )
          as _i3.Future<List<_i5.SellerProduct>>);

  @override
  _i3.Future<void> markAsSold(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSold, [productId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.ProductModel?> getProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue: _i3.Future<_i4.ProductModel?>.value(),
          )
          as _i3.Future<_i4.ProductModel?>);

  @override
  _i3.Future<void> addProduct(_i4.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProduct(_i4.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
